name: 'Publish pack with next dist-tag with npm registry'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testing:
    permissions:
      contents: write
    uses: beuluis/reusable-workflows/.github/workflows/node-qa-testing.yml@main
    secrets: inherit

  publish-npm:
    needs: testing
    uses: beuluis/reusable-workflows/.github/workflows/npm-publish.yml@main
    with:
      dist_tag: 'next'
    secrets: inherit
