name: 'Publish pack with latest dist-tag with npm registry'

on:
  release:
    types:
      - created

jobs:
  testing:
    uses: Beuterei/reusable-workflows/.github/workflows/node-qa-testing.yml@main
    with:
      skip_coverage_report: true
    secrets: inherit

  publish-npm:
    needs: testing
    uses: Beuterei/reusable-workflows/.github/workflows/npm-publish.yml@main
    secrets: inherit
